DROP TABLE IF EXISTS bme_data;

CREATE TABLE IF NOT EXISTS bme_data (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    temp REAL NOT NULL,
    press REAL NOT NULL,
    humid REAL NOT NULL
);

