DROP TABLE IF EXISTS logs;

CREATE TABLE logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    devid TEXT NOT NULL, 
    title TEXT NOT NULL,
    content TEXT NOT NULL
);

